INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER, USER_DATE)
VALUES ('123456789','Juan', 'Alfaro Rojas', 'juan@gmail.com',
 'Central', 'CR', 'San Jose', '00000000','2019-07-01');
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER, USER_DATE)
VALUES ('987654321','Sofia', 'Perez Alfaro', 'sofia@gmail.com',
 'Central', 'CR', 'Alajuela', '00000000','2019-07-02');

INSERT INTO ACCOUNT (USER_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_DATE)
VALUES ((SELECT ID FROM USERS WHERE ID = '123456789'), 'Account 1', 15000, '2019-07-07');
INSERT INTO ACCOUNT (USER_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_DATE)
VALUES ((SELECT ID FROM USERS WHERE ID = '123456789'), 'Account 2', 25000, '2019-07-01');

INSERT INTO ACCOUNT (USER_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_DATE)
VALUES ((SELECT ID FROM USERS WHERE ID = '987654321'), 'Account 3', 35000, '2019-07-01');

INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 1'), 'Card 1', 01, '2019-07-07');
INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 1'), 'Card 2', 23, '2019-07-07');
INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 1'), 'Card 3', 1234, '2019-07-07');
INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 2'), 'Card 1', 45, '2019-07-07');
INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 2'), 'Card 2', 67, '2019-07-07');
INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 3'), 'Card 1', 89, '2019-07-07');
INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 3'), 'Card 2', 1011, '2019-07-07');
INSERT INTO CARD (ACCOUNT_ID, CARD_NAME, CARD_NUMBER, CARD_DATE)
VALUES ((SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_NAME = 'Account 3'), 'Card 3', 1112, '2019-07-07');