CREATE TABLE USER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID VARCHAR(9) NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL_ADDRESS VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  STATE VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(50) NOT NULL,
  DATETIME DATE NOT NULL
);

CREATE TABLE ACCOUNT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID VARCHAR(50) NOT NULL UNIQUE,
  NAME VARCHAR(50) NOT NULL,
  BALANCE BIGINT NOT NULL,
  DATETIME DATE NOT NULL,
  USER_ID VARCHAR(9) NOT NULL
);

CREATE TABLE CARD(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CARD_ID VARCHAR(50) NOT NULL UNIQUE,
  NAME VARCHAR(50) NOT NULL,
  DATETIME DATE NOT NULL,
  ACCOUNT_ID VARCHAR(50) NOT NULL,
);

CREATE TABLE TRANSFER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  AMOUNT BIGINT NOT NULL,
  DATETIME DATE NOT NULL,
  ACCOUNT_ID VARCHAR(50) NOT NULL,
  ACCOUNT_DESTINATION VARCHAR(50) NOT NULL
);