CREATE TABLE USERS(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ID VARCHAR(9) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL_ADDRESS VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  STATE VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(50) NOT NULL,
  USER_DATE DATE NOT NULL
);

CREATE TABLE ACCOUNT(
  ACCOUNT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  ACCOUNT_NAME VARCHAR(50) NOT NULL,
  ACCOUNT_BALANCE BIGINT NOT NULL,
  ACCOUNT_DATE DATE NOT NULL
);

CREATE TABLE CARD(
  CARD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID BIGINT NOT NULL,
  CARD_NAME VARCHAR(50) NOT NULL,
  CARD_NUMBER BIGINT NOT NULL UNIQUE,
  CARD_DATE DATE NOT NULL
);

CREATE TABLE TRANSFER(
  TRANSFER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID BIGINT NOT NULL,
  TRANSFER_AMOUNT BIGINT NOT NULL,
  ACCOUNT_DESTINATION BIGINT NOT NULL,
  TRANSFER_DATE DATE NOT NULL
);